export const REGISTER_START = "REGISTER_START";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT = "LOGOUT";

// USERS
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_USERS_START = "GET_USERS_START";

// ROOMS
export const ADD_ROOM_START = "ADD_ROOM_START";
export const ADD_ROOM_SUCCESS = "ADD_ROOM_SUCCESS";
export const ADD_ROOM_FAIL = "ADD_ROOM_FAIL";

export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";
export const GET_ROOMS_FAIL = "GET_ROOMS_FAIL";
export const GET_ROOMS_START = "GET_ROOMS_START";

// CLIENTS
export const ADD_CLIENT_START = "ADD_CLIENT_START";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_FAIL = "ADD_CLIENT_FAIL";

export const GET_CLIENTS_SUCCESS = "GET_CLIENT_SUCCESS";
export const GET_CLIENTS_FAIL = "GET_CLIENT_FAIL";
export const GET_CLIENTS_START = "GET_CLIENT_START";

// SERVICES
export const ADD_SERVICE_START = "ADD_SERVICE_START";
export const ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS";
export const ADD_SERVICE_FAIL = "ADD_SERVICE_FAIL";

export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const GET_SERVICES_FAIL = "GET_SERVICES_FAIL";
export const GET_SERVICES_START = "GET_SERVICES_START";

// BOOKINGS
export const ADD_BOOKING_START = "ADD_BOOKING_START";
export const ADD_BOOKING_SUCCESS = "ADD_BOOKING_SUCCESS";
export const ADD_BOOKING_FAIL = "ADD_BOOKING_FAIL";

export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
export const GET_BOOKINGS_FAIL = "GET_BOOKINGS_FAIL";
export const GET_BOOKINGS_START = "GET_BOOKINGS_START";

// DEPARTMENTS
export const ADD_DEPARTMENT_START = "ADD_DEPARTMENT_START";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAIL = "ADD_DEPARTMENT_FAIL";

export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
export const GET_DEPARTMENTS_FAIL = "GET_DEPARTMENTS_FAIL";
export const GET_DEPARTMENTS_START = "GET_DEPARTMENTS_START";

// ARTICLES
export const ADD_ARTICLE_START = "ADD_ARTICLE_START";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAIL = "ADD_ARTICLE_FAIL";

export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAIL = "GET_ARTICLES_FAIL";
export const GET_ARTICLES_START = "GET_ARTICLES_START";

// UNITS
export const ADD_UNIT_START = "ADD_UNIT_START";
export const ADD_UNIT_SUCCESS = "ADD_UNIT_SUCCESS";
export const ADD_UNIT_FAIL = "ADD_UNIT_FAIL";

export const GET_UNITS_SUCCESS = "GET_UNITS_SUCCESS";
export const GET_UNITS_FAIL = "GET_UNITS_FAIL";
export const GET_UNITS_START = "GET_UNITS_START";

// IMPORTED ARTICLES
export const ADD_IMPORTED_ARTICLE_START = "ADD_IMPORTED_ARTICLE_START";
export const ADD_IMPORTED_ARTICLE_SUCCESS = "ADD_IMPORTED_ARTICLE_SUCCESS";
export const ADD_IMPORTED_ARTICLE_FAIL = "ADD_IMPORTED_ARTICLE_FAIL";

export const GET_IMPORTED_ARTICLES_SUCCESS = "GET_IMPORTED_ARTICLES_SUCCESS";
export const GET_IMPORTED_ARTICLES_FAIL = "GET_IMPORTED_ARTICLES_FAIL";
export const GET_IMPORTED_ARTICLES_START = "GET_IMPORTED_ARTICLES_START";

// IMPORTED ARTICLES
export const ADD_TICKET_START = "ADD_TICKET_START";
export const ADD_TICKET_SUCCESS = "ADD_TICKET_SUCCESS";
export const ADD_TICKET_FAIL = "ADD_TICKET_FAIL";

export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS";
export const GET_TICKETS_FAIL = "GET_TICKETS_FAIL";
export const GET_TICKETS_START = "GET_TICKETS_START";

export const GET_TICKET_SUCCESS = "GET_TICKET_SUCCESS";
export const GET_TICKET_FAIL = "GET_TICKET_FAIL";
export const GET_TICKET_START = "GET_TICKET_START";
